### ISSUE TITLE
w2grid column's editable with type='select' work ok in v1.5 but NOT work in v2.0

### ISSUE THREAD

**Issue by vinhpt2** [vitmalina/w2ui#2535]
We now have stuck when update application from w2ui v1.5 to w2ui v2.0 because
"w2grid column's editable with type='select' work ok in v1.5 but NOT work in v2.0".
Please fix. Thanks!

**Comment by vinhpt2** [comment]
w2grid column's editable with type='combo' also not work.
Type='list' have error:
"TypeError: query(...).find(...).focus is not a function
    at HTMLDivElement.<anonymous> (w2ui.es6.min.js:475:1023)"

**Comment by vitmalina** [comment]
Type select is deprecated. Use type list. As for combo field, it should work

**Comment by vinhpt2** [comment]
What a pity when 2.0 not support select control when edit grid inline. Can I contribute 100USD for bring it back. Any one want to contribute with me? Thanks in advance.

**Comment by vitmalina** [comment]
Thank you for you offer. I am just curious about type: 'list'. Is there an issue for you to use it? Is is very similar to select and should provide similar experience. Here is a link to the demo page where it is implemented: https://w2ui.com/web/demos/#/grid/21
